### ISSUE TITLE
n3DS C-Stick position not implemented yet

### ISSUE THREAD

**Issue by MissingNO123** [hlixed/TPPFLUSH#1]
Even though it's not supported officially by the library, the C-Stick's position gets stuck to the bottom left corner whenever _any_ data is sent to the 3DS.

**Update:** Changing the default C-Stick values in the library cause it to sometimes get stuck in the straight down position

**Comment by hlixed** [comment]
Sorry about that! As you can see by poking in the library, currently TPPFLUSH just sends a default value for the N3DS c-stick because I haven't implemented the algorithm to determine the proper c-stick command yet. Once that's implemented, it should be easy to find a new default value that doesn't move the c-stick.

In the meantime, if you find a default value that sets the c-stick to neutral, let me know and I'll put it into the library.

**Comment by MissingNO123** [comment]
It seems like any value that I try doesn't work, either I've got the byte order wrong or there's a problem with InputRedirect itself

**Comment by hlixed** [comment]
I know that the byte order is little endian, if that helps.

**Comment by MissingNO123** [comment]
![image](https://user-images.githubusercontent.com/16027333/27140705-3903090a-50f4-11e7-9c33-cf757f65871e.png)
Already tried that.

I was referring to the order of the bytes for C-Stick X, Y, and the ZL/ZR button state but it looks like it's already ordered the right way in the code (X > Y > ZL/ZR)

**Comment by hlixed** [comment]
Try the most recent commit, in which I've implemented ZL and ZR and added some functions to press them. I believe the default value of `bytearray.fromhex("80800081")` should have been `bytearray.fromhex("81008080")` because it's little-endian, so I hope that fixes things. I have no n3DS to test with, though, so would you mind verifying that the new default value doesn't stick to the bottom left?

**Comment by MissingNO123** [comment]
I can verify the new default value is the correct one.
Sending values to the stick works _to some extent_, it gets the correct inputs from the computer, but only updates after pushing and releasing the physical C-Stick itself, after which it sticks to the last value sent to it. Again, this may be an issue with InputRedirect.

**Edit:** C-Stick doesn't work in Smash, it acts as if it's constantly pressed upwards
**Edit 2:** Never mind, it's actually the Circle Pad doing that.
**Edit 3:** InputRedirect is acting extremely unpredictable today, sometimes it works and sometimes it doesn't. I have no idea what's causing any of my issues anymore.

**Comment by hlixed** [comment]
Great! I'll mark the ZLZR button issue, #2, as closed and I'll close this one after I add some functions to move around the c-stick without directly modifying `self.cstick_coords`.

C-stick InputRedirection only updates after pushing the physical c-stick? That's weird. Sounds like it might be time to log an issue in luma3ds.

Thank you for testing!
